services:
  clients-app:
    image: clients-app
    container_name: clients-container
    networks:
      - app-client-network
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

networks:
  app-client-network:
    driver: bridge
