services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    networks:
      - app-client-network
    ports:
      - "5672:5672"
      - "15672:15672"

  clients-app:
    image: clients-app
    container_name: clients-container
    networks:
      - app-client-network
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

networks:
  app-client-network:
    driver: bridge
