version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"

  clients-app:
    image: clients-app
    container_name: clients-container
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

networks:
  app-network:
    driver: bridge
